# === Taps ===
tap "aws/tap"
tap "common-fate/granted"
tap "coursier/formulas"
tap "datawire/blackbird"
tap "github/gh"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "kreuzwerker/taps"
tap "virtuslab/scala-cli"
tap "warrensbox/tap"

# === Core CLI ===
brew "ack"
brew "coreutils"
brew "curl"
brew "fd"
brew "fzf"
brew "gawk"
brew "gnu-sed"
brew "jq"
brew "moreutils"
brew "ripgrep"
brew "tree"
brew "unzip"
brew "watch"
brew "wget"
brew "xmlstarlet"

# === Shell ===
brew "bash"
brew "zsh"
brew "lsd"
brew "thefuck"
brew "tldr"
brew "glow"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-completions"

# === Novelty ===
brew "figlet"
brew "fortune"
brew "hello"
brew "lolcat"

# === Languages & Runtimes ===
brew "go"
brew "node"
brew "nvm"
brew "python@3.13"
brew "perl"
brew "php"
brew "composer"

# === Scala / JVM ===
brew "openjdk"
brew "sbt"
brew "gradle"
brew "gradle-completion"
brew "maven"
brew "coursier/formulas/coursier"
brew "virtuslab/scala-cli/scala-cli"

# === Cloud & Infrastructure ===
brew "awscli"
brew "aws/tap/copilot-cli"
brew "common-fate/granted/granted"
brew "gh"
brew "kubernetes-cli"
brew "kompose"
brew "minikube"
brew "act"
brew "datawire/blackbird/telepresence"
brew "hashicorp/tap/terraform", link: false
brew "kreuzwerker/taps/m1-terraform-provider-helper"
brew "warrensbox/tap/tfswitch"
brew "terraform-docs"
brew "terraform_landscape"
brew "tflint"

# === Databases ===
brew "postgresql@14"
brew "mariadb"
brew "flyway"
brew "parquet-cli"

# === Dev Tools ===
brew "git"
brew "git-extras"
brew "git-open"
brew "gnupg"
brew "neovim"
brew "vim"
brew "pre-commit"
brew "pwgen"
brew "mkcert"
brew "howdoi"
brew "htop"
brew "dockutil"
brew "s3cmd"
brew "datamash"

# === Build Tools ===
brew "autoconf"
brew "automake"
brew "cmake"
brew "gcc"
brew "boost"
brew "physfs"
brew "sdl2"
brew "sdl2_image"
brew "sdl2_ttf"
brew "qemu"
brew "uncrustify"

# === Media ===
brew "ffmpeg"
brew "imagemagick"
brew "graphicsmagick"
brew "ghostscript"
brew "flac"
brew "libsndfile"
brew "vorbis-tools"

# === Networking ===
brew "telnet"
brew "speedtest-cli"

# === Libraries ===
brew "gettext"
brew "openssl@3"
brew "glib"
brew "cairo"
brew "harfbuzz"
brew "pango"
brew "gdk-pixbuf"
brew "gobject-introspection"
brew "librsvg"
brew "libxslt"
brew "libicns"
brew "libmagic"
brew "libidn2"
brew "unbound"
brew "gnutls"
brew "glew"

# === Casks ===
cask "1password-cli"
cask "android-platform-tools"
cask "macfuse"
cask "ngrok"
cask "glance"
cask "syntax-highlight"
cask "qlstephen"
cask "sf"
cask "visual-studio-code"

# === VS Code Extensions ===
vscode "amazonwebservices.codewhisperer-for-command-line-companion"
vscode "dbaeumer.vscode-eslint"
vscode "dotiful.dotfiles-syntax-highlighting"
vscode "dragos.scala-lsp"
vscode "github.vscode-pull-request-github"
vscode "grapecity.gc-excelviewer"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-wsl"
vscode "redhat.java"
vscode "redhat.vscode-commons"
vscode "redhat.vscode-yaml"
vscode "salesforce.salesforce-vscode-slds"
vscode "salesforce.salesforcedx-vscode"
vscode "salesforce.salesforcedx-vscode-apex"
vscode "salesforce.salesforcedx-vscode-apex-replay-debugger"
vscode "salesforce.salesforcedx-vscode-apex-debugger"
vscode "salesforce.salesforcedx-vscode-core"
vscode "salesforce.salesforcedx-vscode-lightning"
vscode "salesforce.salesforcedx-vscode-lwc"
vscode "salesforce.salesforcedx-vscode-soql"
vscode "salesforce.salesforcedx-vscode-visualforce"
vscode "scala-lang.scala"
vscode "scala-lang.scala-snippets"
vscode "scalameta.metals"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
